name: Deploy Flask App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Test Kubernetes connection
        run: kubectl get nodes

      - name: Log in to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.datawiz.io -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t registry.datawiz.io/testk3s/flask-app:${{ github.sha }} .
          docker push registry.datawiz.io/testk3s/flask-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install flask-app ./flask-app -n development --set image.tag=${{ github.sha }}
